/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMDeviceUtilities : NSObject

+ (bool)IMDeviceIsGreenTea;
+ (bool)IMSupportsASTC;

@end
