/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
 */

@interface AudioComponentRegistrar : NSObject <NSXPCListenerDelegate> {
    struct AudioComponentRegistrarImpl { bool x1; bool x2; bool x3; bool x4; id x5; struct function<void (const AudioComponentVector &, AudioComponentVector &)>={type=[24C] {} x6; struct __base<void (const AudioComponentVector &, AudioComponentVector &)> {} *x7; } * mImpl;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void)dealloc;
- (id)initForMode:(bool)arg1;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)resumeListeners;

@end
