/* Generated by RuntimeBrowser.
 */

@protocol FPXRequestHandlingProxyCreating <NSObject>

@required

- (void)fetchProxyForItemIdentifier:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, id, NSError *, void*

@end
