/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.EffectsBrowserViewConstraintManager : SwiftObject {
    void constantConstraints;
    void effectsBrowserViewTopAnchor;
}

@end
