/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKEditCommandObjC : NSObject {
    struct RefPtr<WebKit::WebEditCommandProxy, WTF::DumbPtrTraits<WebKit::WebEditCommandProxy> > { 
        struct WebEditCommandProxy {} *m_ptr; 
    }  m_command;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct WebEditCommandProxy { int (**x1)(); id x2; unsigned long long x3; int x4; struct WebPageProxy {} *x5; }*)command;
- (id)initWithWebEditCommandProxy:(struct Ref<WebKit::WebEditCommandProxy, WTF::DumbPtrTraits<WebKit::WebEditCommandProxy> > { struct WebEditCommandProxy {} *x1; }*)arg1;

@end
