/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKURLSchemeTaskImpl : NSObject <WKObject, WKURLSchemeTaskPrivate> {
    struct ObjectStorage<API::URLSchemeTask> { 
        struct type { 
            unsigned char __lx[24]; 
        } data; 
    }  _urlSchemeTask;
}

@property (readonly) struct Object { int (**x1)(); id x2; }*_apiObject;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSURLRequest *request;
@property (readonly) Class superclass;

- (struct Object { int (**x1)(); id x2; }*)_apiObject;
- (void)_didPerformRedirection:(id)arg1 newRequest:(id)arg2;
- (void)dealloc;
- (void)didFailWithError:(id)arg1;
- (void)didFinish;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveResponse:(id)arg1;
- (id)request;

@end
